name: Nicknamer
version: 0.2
main: me.electroid.nicknamer.NicknamePlugin
author: ElectroidFilms
description: A plugin to test the functionality of randomly generating nicknames.
commands:
   nick:
      description: Give a player a random nickname and skin.
      usage: /nick (player)
   clearnick:
      description: Clear a player's random nickname and skin.
      usage: /clearnick (player)